### ISSUE TITLE
Scope(Class[Apache_c2c::Base]): Could not look up qualified variable 'apache_c2c::root'

### ISSUE THREAD

**Issue by kenorb** [camptocamp/puppet-apache_c2c#119]
I'm testing sample `node central_monitoring_server` as in README of [puppet-nagios](https://github.com/camptocamp/puppet-nagios).

However I've the following errors:

    Debug: Automatically imported apache_c2c::params from apache_c2c/params into production
    Warning: Scope(Class[Apache_c2c::Base]): Could not look up qualified variable 'apache_c2c::root'; class apache_c2c has not been evaluated
    Error: "" is not an absolute path. at /etc/puppet/modules/apache_c2c/manifests/base.pp:11 on node debian-77-wheezy-64-lamp
    Error: "" is not an absolute path. at /etc/puppet/modules/apache_c2c/manifests/base.pp:11 on node debian-77-wheezy-64-lamp

**Comment by mcanevet** [comment]
This module is obsolete, please use `puppetlabs-apache` instead.
